name: Build and Deploy Images

on:
  workflow_dispatch:
  repository_dispatch:
    types: [dependency_updated]

jobs:
  build-api-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout GitHub Action
      uses: actions/checkout@main
      with:
        repository: childmindresearch/ctk-functions

    - name: Build and push image
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . --build-arg AZURE_BLOB_SIGNATURES_CONNECTION_STRING="${{ secrets.AZURE_BLOB_SIGNATURES_CONNECTION_STRING }}" -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/ctk-functions:latest
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/ctk-functions:latest

  build-frontend-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main
        with:
          repository: childmindresearch/ctk-webapp

      - name: Build and push image
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/ctk-webapp:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/ctk-webapp:latest
