name: Build API

on:
  workflow_dispatch:
  repository_dispatch:
    types: [dependency_updated]

jobs:
  services:
    languagetool:
      image: erikvl87/languagetool:6.5
      ports:
        - 8010:8010
    api:

